#!/bin/sh /tmp/.luci/etc/rc.common

START=99
STOP=0

TEMP_CONFIG='/tmp/config.yaml'

config_load "pod_clash"
config_get POD_NAME pod "pod_name"
config_get POD_CONFIG pod "pod_config"
config_get UCI_CONFIG global "config"

config_load "pod_clash_general_${UCI_CONFIG}"
config_get CLASH_SECRET general "secret"
config_get CLASH_controller general "external_controller"
CLASH_PORT=$(echo ${CLASH_controller} | cut -d: -f2)
POD_IP=

live_check(){
  if [ "$(docker inspect --format '{{ .State.Status }}' ${POD_NAME})" == "running" ]; then
    POD_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${POD_NAME})
  fi
}

gen_config(){
  lua -l "luci.model.pod_clash" -e "print(_clash.gen_config(\"${UCI_CONFIG}\"))" > ${TEMP_CONFIG}
  docker cp ${TEMP_CONFIG} ${POD_NAME}:${POD_CONFIG}
}

apply_config(){
  # return http code only
  stat=$(curl -s -w "%{http_code}" -X PUT -H "Authorization: Bearer ${CLASH_SECRET}" -H "Content-Type: application/json" -d "{\"path\":\"${POD_CONFIG}\"}" ${POD_IP}:${CLASH_PORT}/configs)
  if [ "$stat" -lt 300 ]; then
    echo "success"
  else
    echo $stat
  fi
}

start() {
  live_check && gen_config && apply_config
}